#pragma once
#include <windows.h>

UINT64 CALLBACK hash_0(_In_ CONST INT64, _In_ CONST UINT64);
UINT64 CALLBACK hash_1(_In_ CONST INT64, _In_ CONST UINT64);
UINT64 CALLBACK hash_2(_In_ CONST INT64, _In_ CONST UINT64);
UINT64 CALLBACK hash_3(_In_ CONST INT64, _In_ CONST UINT64);

UINT64 CALLBACK hash_universal(_In_ CONST INT64, _In_ CONST UINT64);